#!/bin/sh -l
#PBS -j oe
#PBS -N 'gmx_shear'
#PBS -l nodes=1:ppn=16
#PBS -l walltime=96:00:00
#PBS -q batch
#PBS -M dpert@umich.edu
#PBS -m abe 
#PBS -e /home/danielpert/TRUE-nanotribology/workflow/PBS/gmx_shear_error.txt
#PBS -o /home/danielpert/TRUE-nanotribology/workflow/PBS/gmx_shear_output.txt

cd /home/danielpert/TRUE-nanotribology/workflow/example_simulation  # This is the location wherever you called the qsub command
echo `cat $PBS_NODEFILE`
# Loading the software you need
module load gromacs/2018.7
module load lammps/30Jun2020
# Run the command, either python code or simulation
# Grompp
gmx grompp -f ../util/mdp_files/shear_5nN.mdp -c compress.gro -p init.top -n init.ndx -o shear_5nN.tpr -maxwarn 3
# Run GROMACS
gmx mdrun -v -nt 16 -s shear_5nN.tpr -deffnm shear_5nN -cpi shear_5nN.cpt -cpo shear_5nN.cpt -noappend -gpu_id 01







