#!/bin/sh -l
#PBS -j oe
#PBS -N NVT_equilibrate
#PBS -l nodes=1:ppn=16
#PBS -l walltime=96:00:00
#PBS -q batch
#PBS -M dpert@umich.edu
#PBS -m abe 
#PBS -e /home/danielpert/TRUE-nanotribology/workflow/PBS/NVT_equilibrate_error.txt
#PBS -o /home/danielpert/TRUE-nanotribology/workflow/PBS/NVT_equilibrate_output.txt

cd /home/danielpert/TRUE-nanotribology/workflow/example_simulation  # This is the location wherever you called the qsub command
echo `cat $PBS_NODEFILE`
# Loading the software you need
module load gromacs/2018.7
module load lammps/30Jun2020
# Run the command, either python code or simulation
# Grompp
gmx grompp -f ../util/mdp_files/nvt.mdp -c em.gro -p init.top -n init.ndx -o nvt.tpr -maxwarn 2
# Run GROMACS
gmx mdrun -v -deffnm nvt -s nvt.tpr -cpi nvt.cpt -nt 16 -gpu_id 01









